name: MSDO Security Scan

# Workflow disabled - uncomment to re-enable
on:
   push:
     branches: [ main, master ]
   pull_request:
     branches: [ main, master ]
   workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  msdo-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Run Microsoft Security DevOps Action
      uses: microsoft/security-devops-action@latest
      with:
        tools: 'checkov'

